name       : tevent
version    : 0.13.0
release    : 16
source     :
    - https://www.samba.org/ftp/tevent/tevent-0.13.0.tar.gz : b9437a917fa55344361beb64ec9e0042e99cae8879882a62dd38f6abe2371d0c
homepage   : https://tevent.samba.org
license    : LGPL-3.0-or-later
component  : programming
summary    : Tevent is an event system based on the talloc memory management library
description: |
    Tevent is an event system based on the talloc memory management library
builddeps  :
    - pkgconfig(cmocka)
    - pkgconfig(talloc)
setup      : |
    # uses a custom configure script which is not created by GNU autoconf
    # and doesn't understand the --runstatedir option.
    ./configure $(sed 's|--runstatedir=/run||g' <<< "%CONFOPTS%") \
      --bundled-libraries=NONE \
      --builtin-libraries=replace \
      --disable-rpath-install \
      --disable-python
build      : |
    %make
install    : |
    %make_install
# check      : |
# Disable tests until upstream get it together
#    %make check
