name       : tevent
version    : 0.11.0
release    : 15
source     :
    - https://www.samba.org/ftp/tevent/tevent-0.11.0.tar.gz : ee9a86c8e808aac2fe1e924eaa139ff7f0269d0e8e4fafa850ae5c7489bc82ba
license    : LGPL-3.0-or-later
component  : programming
summary    : Tevent is an event system based on the talloc memory management library
description: |
    Tevent is an event system based on the talloc memory management library
builddeps  :
    - pkgconfig(cmocka)
    - pkgconfig(talloc)
setup      : |
    %configure \
      --bundled-libraries=NONE \
      --builtin-libraries=replace \
      --disable-rpath-install \
      --disable-python
build      : |
    %make
install    : |
    %make_install
# check      : |
# Disable tests until upstream get it together
#    %make check
