name       : tevent
version    : 0.9.33
release    : 4
source     :
    - https://www.samba.org/ftp/tevent/tevent-0.9.33.tar.gz : 22712ee981fd4298fcd5f3afb27d87a72257cebad37812cfbd3da5d968ed1bdc
license    : LGPL-3.0
component  : programming
summary    : Tevent is an event system based on the talloc memory management library
description: |
    Tevent is an event system based on the talloc memory management library
builddeps  :
    - pkgconfig(talloc)
setup      : |
    %configure --bundled-libraries=NONE \
               --builtin-libraries=replace
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
