name       : tevent
version    : 0.9.36
release    : 8
source     :
    - https://www.samba.org/ftp/tevent/tevent-0.9.36.tar.gz : bd2b6be3fd1601ed7f176e99111e322c57d58e425cc149ee80c7dd4fed263b4c
license    : LGPL-3.0
component  : programming
summary    : Tevent is an event system based on the talloc memory management library
description: |
    Tevent is an event system based on the talloc memory management library
builddeps  :
    - pkgconfig(talloc)
setup      : |
    %configure --bundled-libraries=NONE \
               --builtin-libraries=replace \
               --disable-rpath-install
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
