name       : tevent
version    : 0.9.31
release    : 1
source     :
    - https://www.samba.org/ftp/tevent/tevent-0.9.31.tar.gz : 4a13f2256ad804c860e84068258bd0f8be31cf0c79aa8f3019fa32f6928c2bfc
license    : GPL-3.0
component  : programming
summary    : Tevent is an event system based on the talloc memory management library
description: |
    Tevent is an event system based on the talloc memory management library
builddeps  :
    - gcc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
