name       : tevent
version    : 0.9.39
release    : 10
source     :
    - https://www.samba.org/ftp/tevent/tevent-0.9.39.tar.gz : f68d0fcc616119d27ebace162499e73f4ae3998e49b98d1f454bb467cdb1d4e6
license    : LGPL-3.0-or-later
component  : programming
summary    : Tevent is an event system based on the talloc memory management library
description: |
    Tevent is an event system based on the talloc memory management library
builddeps  :
    - pkgconfig(talloc)
setup      : |
    %configure \
      --bundled-libraries=NONE \
      --builtin-libraries=replace \
      --disable-rpath-install \
      --disable-python
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
